# Site settings

#theme: jekyll-theme-minimal
#theme: jekyll-theme-so-simple
title: Søren Brinck Knudstorp3
description: Søren's personal website

# GitHub Pages settings
plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/so-simple-theme@3.2.0

url: "https://knudstorp.github.io"
