# Site settings
title: Søren Brinck Knudstorp
description: Søren's personal website
#theme: jekyll-theme-minimal
#theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: mmistakes # site's Twitter username

  # Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# GitHub Pages settings
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme@3.2.0
#logo
