# Site settings
title: Søren Brinck Knudstorp
description: Søren's personal website b1b
#theme: jekyll-theme-minimal

# GitHub Pages settings
#plugins:
#  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme@3.2.0
