# Site settings

#theme: jekyll-theme-minimal
#theme: jekyll-theme-so-simple
title: Søren Brinck Knudstorp22
description: Søren's personal website

# GitHub Pages settings
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/
remote_theme: mmistakes/so-simple-theme@3.2.0

url: "https://knudstorp.github.io"
logo: logo-no-background, resized.png

skin: "/assets/css/skins/default.css"
#skin: "/assets/css/skins/dark.css"
#skin: "/assets/css/skins/light.css"

date_format: "%d-%m-%Y"
locale: en-us
mathjax:
  enable: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"


author:
  name: Søren Brinck Knudstorp
  #twitter: johndoetwitter
  #picture: /images/johndoe.png

footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/s%C3%B8ren-brinck-knudstorp/
    icon: fab fa-linkedin
  - title: Twitter
    url: https://twitter.com/knudstorp
    icon: fab fa-twitter-square
  - title: Mail
    url: "mailto:s.b.knudstorp@uva.nl"
    icon: fab fa-envelope  
  #- title: GitHub
  #  url: https://github.com/knudstorp
  #  icon: fab fa-github-square
  #- title: Feed
  #  url: atom.xml
  #  icon: fas fa-rss-square

copyright: "© 2023 Søren Brinck Knudstorp"
