# Site settings
title: Søren Brinck Knudstorp
description: Søren's personal website
#theme: jekyll-theme-minimal
theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme@3.2.0
skin: "/assets/css/skins/default.css"
locale: en-US

# GitHub Pages settings
plugins:
  - jekyll-remote-theme

