# Site settings
title: Søren Brinck Knudstorp
description: Søren's personal website
#theme: jekyll-theme-minimal
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
date_format: "%B %-d, %Y"

# GitHub Pages settings
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme@3.2.0
logo 


# Site Author
author:
  name: Søren Brinck Knudstorp
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:
