# Site settings
title: Søren Brinck Knudstorp11
description: Søren's personal website b1b
#theme: jekyll-theme-minimal
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US

# GitHub Pages settings
plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme@3.2.0
logo 
